---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-guacamole
      ansible.builtin.include_role:
        name: heicloud_windows_ansible.base_roles.install_mssql
      vars:
        mssql_sysadmin_accounts:
          - vagrant
