name: Molecule Test

on: [push]

jobs:
  molecule-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          pip3 install molecule molecule-vagrant
      - run: |
          molecule test
